version: '3.7'
services:
    go-app:
      build:
        context: .
      container_name: muxSqlApp
      ports:
        - "8010:8010"
      depends_on:
        - postgres
      networks:
        - keploy-network 

    postgres:
        image: postgres:10.5
        container_name: mux-sql-postgres-1
        environment:
          - POSTGRES_DB=postgres
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=password
        ports:
          - '5432:5432'
        volumes: 
          # - ./postgres-data:/var/lib/postgresql/data
          # copy the sql script to create tables
          - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
          - keploy-network

networks:
  keploy-network:
    external: true