version: "3.9"
services:
  go-app:
    build:
      context: .
    container_name: userProfileApp
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    networks:
      - keploy-network  
  
  mongo:
    image: "mongo"
    container_name: mongoDb
    ports:
    - "27017:27017"
    networks:
      - keploy-network

networks:
  keploy-network:
    external: true