name: sample-tests
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  e2e-test:
    runs-on: ubuntu-latest
    steps:
    - name: Test-Report
      uses: keploy/testgpt@main
      with:
        working-directory: gin-mongo
        delay: 20
        keploy-path: ./
        command: go run .
